Repository Mavv3006/mathbase, pull requests merged in 2020-05, with the labels that each got.

#16 added html markup for login and register form
  html/forms/login.html
  html/forms/register.html
Labels: enhancement

#15 added postgresql database export
  sql/mysql-script.sql
  sql/postgresql-script.sql
Labels: bug

#21 added config.php
  config/config.php
  database/Database.php
Labels: enhancement

#20 changed to MySQL database
  sql/mysql-script.sql
Labels: bug

#27 Added Footer
  css/footer.css
  html/footer.php
  index.php
Labels: enhancement

#28 created header
  assets/pp_default.svg
  css/header.css
  html/header.php
  index.php
Labels: enhancement

#32 Feature/added exercises list
  css/exercise.css
  css/exercise_list.css
  database/Database.php
  html/exercise_list.php
  html/head.php
  index.php
  pages/exercise.php
  viewModel/CategoryViewModel.php
  viewModel/DifficultyViewModel.php
  viewModel/ExerciseViewModel.php
  viewModel/SubcategoryViewModel.php
  viewModel/UserViewModel.php
Labels: enhancement

#39 removed roles from README.md
  README.md
Labels: documentation

#41 added exercise picture and profile picture database support
  assets/exercise_default.svg
  css/exercise.css
  css/footer.css
  models/Exercise.php
  models/User.php
  pages/exercise.php
  sql/mysql-structur.sql
Labels: bug, enhancement

#48 new sql script version
  sql/mysql-script.sql
  sql/mysql-structur.sql
  sql/postgresql-script.sql
Labels: bug

#44 Feature/add new exercise page
  auth/user_info.php
  css/new_exercise.css
  database/Database.php
  inc/save_exercise.php
  models/Exercise.php
  models/User.php
  pages/exercise.php
  pages/new_exercise.php
  viewModel/CategoryViewModel.php
  viewModel/DifficultyViewModel.php
  viewModel/ExerciseViewModel.php
  viewModel/SubcategoryViewModel.php
  viewModel/UserViewModel.php
  viewModel/ViewModel.php
Labels: enhancement

#53 Inhalte hinter Footer versteckt
  css/footer.css
  pages/exercise.php
Labels: bug

#54 Neue Index-Seite erstellt
  css/index.css
  index.php
  main.php
Labels: enhancement

#55 Connect Login
  .gitignore
  auth/logout.php
  auth/sign_in.php
  auth/sign_up.php
  auth/user_info.php
  config/config.php
  database/Database.php
  html/header.php
  html/menu.php
  html/profile.php
  index.php
  pages/exercise.php
  viewModel/UserViewModel.php
Labels: bug, enhancement

#58 bug/imports-without-slash
  html/menu.php
Labels: bug

#59 bugfix/require_once-statt-include
  css/footer.css
  database/CategoryDatabase.php
  database/DifficultyDatabase.php
  database/ExerciseDatabase.php
  database/SubcategoryDatabase.php
  html/exercise_list.php
  html/header.php
  html/menu.php
  html/profile.php
  index.php
  main.php
  models/Category.php
  models/Difficulty.php
  models/Exercise.php
  models/Subcategory.php
  models/User.php
  pages/exercise.php
  pages/new_exercise.php
  viewModel/CategoryViewModel.php
  viewModel/DifficultyViewModel.php
  viewModel/ExerciseViewModel.php
  viewModel/SubcategoryViewModel.php
  viewModel/UserViewModel.php
Labels: bug

#61 Rechtschreibfehler im Import korrigiert
  auth/user_info.php
Labels: bug
